[package]
name = "topos-uci"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
ethereum-types.workspace = true
bincode.workspace = true
thiserror.workspace = true
keccak-hash = "0.10.0"
