[package]
name = "topos-uci"
version = "0.1.1"
edition = "2021"

[dependencies]
bincode.workspace = true
ethereum-types.workspace = true
hex.workspace = true
keccak-hash = "0.10.0"
serde = { workspace = true, features = ["derive"] }
thiserror.workspace = true
